//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchDetail
    {
        public int Id { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> Seats { get; set; }
        public Nullable<int> CollageId { get; set; }
        public string Fees { get; set; }
    
        public virtual CollageDetail CollageDetail { get; set; }
    }
}
